version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: template_postgres
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
