version: '3.8'

services:
  users-service:
    extends:
      file: ./microservice-poc/docker-compose.yml
      service: users-service

  postgres:
    extends:
      file: ./microservice-poc/docker-compose.yml
      service: postgres
