services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=system
      - APP_USER_PASSWORD=oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./ojdbc11.jar:/kafka/connect/kafka-connect-jdbc/ojdbc11.jar
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/ as sysdba", "<<< 'select 1 from dual;'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - microservice_net

networks:
  microservice_net:
    external: true
    
volumes:
  oracle_data:
