networks:
  microservices:
    name: microservices
    driver: bridge

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - LOG_LEVEL=debug
    ports:
      - "3000:3000"
    networks:
      - microservices
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  consul:
    image: hashicorp/consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - microservices
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
