FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY nest-cli.gateway.json ./nest-cli.json
COPY tsconfig*.json ./
COPY src ./src
COPY config ./config

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["node", "dist/gateway-service/main"]
