services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres-users-${INSTANCE_ID:-1}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_service_${INSTANCE_ID:-1}
      - NODE_ENV=production
      - INSTANCE_ID=${INSTANCE_ID:-1}
    hostname: "users-service-${INSTANCE_ID:-1}"
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      postgres-users-${INSTANCE_ID:-1}:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - microservice_net

  postgres-users-${INSTANCE_ID:-1}:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_service_${INSTANCE_ID:-1}
      - POSTGRES_MAX_CONNECTIONS=200
    volumes:
      - postgres_data_users_${INSTANCE_ID:-1}:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservice_net

networks:
  microservice_net:
    driver: bridge
    
volumes:
  postgres_data_users_1:
  postgres_data_users_2:
  postgres_data_users_3:
