services:
  consul:
    image: hashicorp/consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"  # HTTP API and UI
      - "8600:8600/tcp"  # DNS
      - "8600:8600/udp"  # DNS
    command: "agent -dev -client=0.0.0.0"
    network_mode: "host"
